### ISSUE TITLE
Show correct path in error message when file is included

### ISSUE THREAD

**Issue by rodion-k** [phug-php/phug#12]
Hello,

I encountered an issue with the following code:
// view.pug
```pug
extends layout

block content
  p test
```
// layout.pug
```pug
doctype

p= $undefined()

block content
```

I expected to get:
```
Function name must be a string on line 3, offset 2

    1 | doctype
    2 | 
>   3 | p= $undefined()
---------^
    4 | 
    5 | block content
````

But I actually get:
```
Function name must be a string on line 3, offset 2

   1 | extends layout
    2 | 
>   3 | block content
---------^
    4 |   p test
```
[Pull request](https://github.com/phug-php/compiler/pull/24)
Thanks!

**Comment by kylekatarnls** [comment]
Thanks a lot, it's totally relevant, I prepare some unit tests in the renderer and I merge it.

**Comment by kylekatarnls** [comment]
It's merged, you can update the compiler to get it.
