### ISSUE TITLE
Output buffering in sandbox make it hard to dump variables for debugging

### ISSUE THREAD

**Issue by char101** [phug-php/phug#14]
Hello,

As the title says, is there any way to output `var_dump`s within code that runs inside phug's sandbox?

I'm debugging on why phug cannot find the parent template when using template inheritance, and I `dump`ed some variable values. Specifically I'm using symfony's `var-dumper`. The problem is that the script and styles that are added by `var-dumper` does not appear in the output html. On further investigation I found out that the first dump was eaten by phug's sandbox.

Also what is the purpose of the sandbox? I don't find any occurence where the sandbox buffer is used in the code.

**Comment by kylekatarnls** [comment]
Hi,

First, variables values cannot have any impact on inheritance as extend and include in pug are all static handled at compile-time, not render-time.

The SandBox render the template in a safe  area to be sure if an exception occurs, we won't display partial output, and then in debug mode, we can display error with line and offset in the pug source file.

Do you use [pug-symfony](https://github.com/pug-php/pug-symfony)?

**Comment by char101** [comment]
I'm using phug directly. I don't use the symfony framework, only the var-dumper. Since I'm using phug directly, I need to learn how to use it to integrate with my application, so some `dump` here and there is necessary to learn how it works.

Currently I'm trying to send the dump output to an UDP server, which will also serve a websocket to a HTML page which will display the results. Therefore it will not be affected by any output buffering headache in PHP.

But in the long run I think this could cause some hard to debug problem when the user want to output something and it is running inside the sandbox, because there will be nothing printed. I even have to use something like [uopz](https://github.com/krakjoe/uopz) to track where the calls to `ob_start` are made.

**Comment by char101** [comment]
As an easy solution, maybe an option to enable/disable the sandbox?

I think in development, the user could be interested in any partial/exception output that occurs. It can be disabled on production environment only.

**Comment by kylekatarnls** [comment]
First I need to understand exactly we are trying to solve because the following code works perfectly:
```pug
p Before
- var_dump($pageTitle)
p After
```
If the var_dump works, the xdebug or symfony dump should work too. Else it's a bug from this particular function.

How many ob_start() are used should not be something you need to care about.

Last, it seems to me disable features to get debug info is the wrong approach. We should keep prod and dev environments close enough to not have surprises when deploying on production.

Short-circuit sandbox really sounds like a hack to me. We don't want to put wheels on the roof of our car to drive it upside down.

**Comment by char101** [comment]
I have completed by udp debug collector, so I guess I'll close this issue for now. Thanks.

Just for the record, I was debugging the value of `$paths` in [Compiler.php#L309](https://github.com/phug-php/compiler/blob/master/src/Phug/Compiler.php#L309) because it change itself relative to the path of the rendered template instead of using the value given when constructing the `Renderer`.

![2017-12-08 16_48_02-debug view - firefox developer edition](https://user-images.githubusercontent.com/71255/33760335-d609a82a-dc37-11e7-8b39-500f43cd52c0.png)

The template is `views/welcome/index.pug` which extends `views/default.pug`.

**Comment by kylekatarnls** [comment]
Hi, can you precise what was unexpected in the paths calculation and what was the extend code used (relative or absolute path) if it's a non-documented behavior?

**Comment by char101** [comment]
It look like if I write `extends template.pug` it is calculated relative to the current template path. How should I write it if I want it to be relative to the `paths` option without having to write it in absolute path?

I'm thinking about changing this line in [Compiler.php#L309](https://github.com/phug-php/compiler/blob/master/src/Phug/Compiler.php#L309)

```php
$paths = $paths ?: $this->getOption('paths');
```

into

```php
$paths = ($paths ?? []) + $this->getOption('paths');
```

**Comment by kylekatarnls** [comment]
"relative to the paths" is exactly what absolute path do. Why do you not want to use absolute paths?
https://phug-lang.com/#includes
https://phug-lang.com/#paths

**Comment by char101** [comment]
So if the value of `paths` is `/application/views`, and the current template is `/application/views/welcome/index.pug` which should extends `/application/views/default.pug`, how should I write the `extends` line? Because `extends default.pug` does not work, it looks for `default.pug` in `/application/views/welcome`.

**Comment by char101** [comment]
Oh Ok I misunderstood, so `extends /options.pug` is taken to relative to `paths`.

**Comment by char101** [comment]
Now I got

```
 Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 98570240 bytes) in vendor/phug/renderer/src/Phug/Renderer/Partial/Debug/DebuggerTrait.php on line 81
```

Back to debugging I guess.

**Comment by char101** [comment]
`print_r` in [DebuggerTrait.php#L81](https://github.com/phug-php/renderer/blob/master/src/Phug/Renderer/Partial/Debug/DebuggerTrait.php#L81) will fail if the parameters contains circular reference.

**Comment by kylekatarnls** [comment]
The point is Phug (as in pugjs) will have its own directory root. Use the file system root would be useless as the same templates as supposed to be shared between several developers and environments. So we allow to specify one or more root directory like you may do it for the URL root of your app in Apache, nginx, etc.

For your allowed memory exception. You can try to set debug option to false, but it's more likely an application problem, there are many possible reasons like:
- import loop (for example: foo.pug includes bar.pug and bar.pug extends foo.pug).
- each/for/while infinite loop with some memory allocation inside.
- you call an helper/getter/function from the templates.

**Comment by kylekatarnls** [comment]
Arf, yes, see your edit. Will see how we can prevent that. Wich version of PHP do you use?

**Comment by char101** [comment]
Absolute path usually means relative to the filesystem root, that's why I didn't get it at first.

I'm using PHP 7.2.

**Comment by char101** [comment]
What do you think about using symfony's var-dumper. I tried using it and it works fine.

```php
'parameters'  => $parameters ? (new \Symfony\Component\VarDumper\Dumper\HtmlDumper)->dump((new \Symfony\Component\VarDumper\Cloner\VarCloner)->cloneVar($parameters), true): '',
```

**Comment by kylekatarnls** [comment]
Yes, I was looking fr the symfony var-dumper. And as it's a stand-alone module, it's a very good option.

**Comment by kylekatarnls** [comment]
Hi, you can update to get the renderer 0.3.3 with the new var dumper.
