### ISSUE TITLE
Shared variables lost when cache enabled

### ISSUE THREAD

**Issue by Illvili** [phug-php/phug#19]
Hello,

I encountered an issue with the following code:
```php
<?php
use Pug\Pug;

include 'vendor/autoload.php';

$pug = new Pug([
    'shared_variables' => [
        'foo' => 123
    ],
    'cache' => __DIR__ . '/cache'
]);

$pug->display('p=foo');

```

I expected to get:
```html
<p>123</p>
```

But I actually get:
```html
<p></p>
```

So I found something here: [Phug\Renderer\Partial\AdapterTrait line 94](https://github.com/phug-php/renderer/blob/a59288cf2cd013b8d263fa91ddedc84c13e660db/src/Phug/Renderer/Partial/AdapterTrait.php#L94)
```php
$adapter->displayCached($path, $input, $getSource, $parameters);
```
change it to:
```php
$adapter->displayCached($path, $input, $getSource, $this->mergeWithSharedVariables($parameters));
```
could solve this.

Does this change cause someting error?

Additional, at first I try to use `Phug` with js style expression, when cache enable it fail with
> You cannot use "cache_dir" option with Phug\Renderer\Adapter\EvalAdapter because this adapter does not implement Phug\Renderer\CacheInterface

Thanks!

**Comment by kylekatarnls** [comment]
Hello,

Indeed `$parameters` should always be used with `mergeWithSharedVariables` before a rendering. I will fix it.

Can you give me the PHP code of your second error (with Phug)?

**Comment by kylekatarnls** [comment]
You second problem should now also be fixed by updating with `composer update`

**Comment by Illvili** [comment]
Every thing work fine, thanks!
