### ISSUE TITLE
.length parameter of array

### ISSUE THREAD

**Issue by khades** [phug-php/phug#25]
PugJS has ability to return length of array is you call "length" parameter, php-yii2, which uses phug does not use it. Will this feature be implemented?

**Comment by kylekatarnls** [comment]
Hi, it's possible to implement it but you should be aware that all your template is converted into PHP, no into JS. To get a 100% full-support of the JS engine (you loose PHP stuff inside your templates in counter part), then you can see our Alternatives section in the documentation: https://phug-lang.com/#alternatives

While I will think of the features and possible side effects, you can use the PHP `count` function:

```pug
p=count(myArray)
```

**Comment by kylekatarnls** [comment]
Hi, `.length` is now available on strings and arrays. You can use `composer update` to get this new feature.
