### ISSUE TITLE
Array access in multiline attributes

### ISSUE THREAD

**Issue by rodion-k** [phug-php/phug#28]
Hello,

I encountered an issue with the following code:
```pug
- $test=['id' => 1]
p(
  id=$test['id']
) test
```

I expected to get:
```html
<p id="1">test</p>
```

But I actually get:
rendering hangs

Thanks!

**Comment by rodion-k** [comment]
[this loop](https://github.com/phug-php/lexer/blob/8749c7e36b149069902bdc049fe71aa86f7bf9c7/src/Phug/Lexer/Scanner/AttributeScanner.php#L89) never ends

**Comment by kylekatarnls** [comment]
With which pug code?

**Comment by rodion-k** [comment]
```pug
- $test=['id' => 1]
p(
  id=$test['id']
) test
```

**Comment by kylekatarnls** [comment]
Oh OK, you found the cause of the hang, awesome! Thanks. Could be quick fixed now.

**Comment by rodion-k** [comment]
And another error with attributes:
```pug
- $test=1
p(
  id=empty($test) ? '' : $test
) test
```
PHP Parse error:  syntax error, unexpected ')' in /vendor/phug/renderer/src/Phug/Renderer/Adapter/EvalAdapter.php(12) : eval()'d code on line 207

**Comment by kylekatarnls** [comment]
Hi, please run `composer update`, it should be fixed.
