### ISSUE TITLE
Accessing globals like $_SERVER

### ISSUE THREAD

**Issue by a666** [phug-php/phug#35]
Hello,

I am trying to understand the following behavior:
with `$_SERVER['URL'] = 'https://example.com' `
```pug
- $url = $_SERVER['URL']
a(href=$url) test1
a(href=$_SERVER['URL']) test2
```

I expected to get:
```html
<a href="https://example.com">test1</a>
<a href="https://example.com">test2</a>
```

But I actually get:
```html
<a>test1</a>
<a href="https://example.com">test2</a>
```

Is there a way to assign $_SERVER['URL'] to a variable in the same pug file? 

Thanks!

**Comment by kylekatarnls** [comment]
First, if you use the option `'expressionLanguage' => 'php'`, you code will work just fine. But you have to choice a expression style (they cannot be mixed in the same template).
```php
$pug = new Pug([
  'expressionLanguage' => 'php',
]);
```

If you want to keep JS-style, you simply should pass variables you need as locals:
**template.pug**:
```pug
a(href=host) test1
a(href=server['HTTP_HOST']) test2
```
```php
$pug = new Pug([
  'expressionLanguage' => 'js', // default value
]);
$pug->renderFile('template.pug', [
  'host' => $_SERVER['HTTP_HOST'], // use only the specific value you need (recommended)
  'server' => $_SERVER, // or give access to the whole superglobal (not recommended)
]);
```

**Comment by a666** [comment]
Wonderful.
Solved, thank you.
