### ISSUE TITLE
Bug in parser

### ISSUE THREAD

**Issue by AlexanderGogolev** [phug-php/phug#39]
Hello,

I encountered an issue with the following code:
```pug
body
  if (test == true)
    h1 Phug
  else
    <!---->
  div test
```

I expected to get:
```html
<body>
  <h1>Phug</h1>
  <div>test</div>
</body>

```

But I actually get:
```html
<body>
  <h1>Phug</h1>
</body>
```

Thanks!

**Comment by AlexanderGogolev** [comment]
this code work in pug.js

**Comment by AlexanderGogolev** [comment]
this work in version 2.7.5

**Comment by kylekatarnls** [comment]
Hi, I will check if we should handle this. The `<` mark RAW string output start.

But in any case, you should prefer:

```pug
body
  if (test == true)
    h1 Phug
  else
    //
  div test
```
for comments;

and:
```pug
body
  if (test == true)
    h1 Phug
  else
    | <!---->
  div test
```
for unescaped one-line string output. Both will work around the bug you get.

**Comment by AlexanderGogolev** [comment]
Thank )

**Comment by kylekatarnls** [comment]
Fixed, you can run `composer update` to get the new lexer version.
