### ISSUE TITLE
accessing $block returns true, but nothing about the content

### ISSUE THREAD

**Issue by BananaAcid** [phug-php/phug#58]
Hello,

I encountered an issue with the following code:
```pug
mixin item()
    - $newBlock = strip_tags($block);
    div= $newBlock
+item()
    | <b>hello</b>
```

First I thought, $block would be a function or class that would hold the content - but var_dump($block) results in (bool)true

I expected to get:
```html
hello
```

But I actually get:
```html
<div>1</div>
```

Thanks!

**Comment by kylekatarnls** [comment]
The only purpose of `block` variable is to know from inside the mixin declaration if the block have been filled or not on call. So to do `if block` as a boolean answer. If someone made a strict test `if block === true` changing the content of `$block` will break this app.

As it's a breaking change I won't change the `$block` variable.

Now there is still `__pug_children(get_defined_vars())` to actually trigger manually the block. But it displays it, it does not return it.

In your example, it looks feasible but `$__pug_children` is a closure that take locals variable and actually output in the sdtout.

So you need to catch the output:
```pug
mixin item
  - ob_start()
  - __pug_children(get_defined_vars())
  - content = ob_get_contents()
  - ob_end_clean()
  div=strip_tags(content)

+item
  | <b>hello</b>
```

It sounds still a bit like a tweaked pattern. Can you explain why you would add tags in mixin blocks then remove them from inside the mixin declaration ?

**Comment by BananaAcid** [comment]
Thanks for the reply. Works great!

I have 2 reasons.
1. I modified the item mixin to export all data (also **block** data) to a CSV. (was statically build with pugjs to html)
2. changing the page, to parse the pug (and cache) through phug and taking the data dynamically from a csv/database I keep the structure, but need to pass the data in and prevent tags from appearing (script tags and so on) - this will keep the original pug file close to what it was, and does some additional stuff in the item mixin file

By any chance, do you know how to get the block data in pugjs?

**Comment by kylekatarnls** [comment]
It will be difficult, in pugjs, `block`variable is a function doing basically:
`function(){
  pug_html = pug_html + "<p>";
  pug_html = pug_html + "foo</p>";
}`
