### ISSUE TITLE
Consecutive interpolation results in wrong output

### ISSUE THREAD

**Issue by char101** [phug-php/phug#65]
Hello,

I encountered an issue with the following code:
```pug
- $a = 10
- $b = 11
| (#{$a}#{$a != $b ? ' - '.$b : ''})
```

I expected to get:
```html
(10 - 11)
```

But I actually get:
```html
(10< - 11>)</ - 11>
```

Thanks!

**Comment by kylekatarnls** [comment]
This is a bug, meanwhile you may check https://github.com/phug-php/phug/issues/64#issuecomment-610240466

**Comment by kylekatarnls** [comment]
Consecutive interpolation has been fixed, now this code output exactly what you expect. It will be fixed in the next release, but you can yet test it with `"phug/phug": "dev-master"`

**Comment by kylekatarnls** [comment]
1.7.1 released with this fixed.
