### ISSUE TITLE
Incomplete interpolation does not trigger error

### ISSUE THREAD

**Issue by char101** [phug-php/phug#70]
Hello,

I encountered an issue with the following code:
```pug
p.
  a #[a(href='') 
  b] c
```

I expected to get:
```
index.pug:2:18
    1| p.
  > 2|   a #[a(href='') 
------------------------^
    3|   b] c

End of line was reached with no closing bracket for interpolation.
```

But I actually get:
```html
<p>a <a href=""></a><b></b> c
</p>
```

Thanks!

**Comment by kylekatarnls** [comment]
Indeed, pugjs is right to disallow new lines inside interpolation, as it would be very unsafe to use them.

**Comment by kylekatarnls** [comment]
Pugjs disallow interpolations `#{}` and tag interpolations `#[]` the same way. But multi-line interpolation can be a convenient feature for expressions:

```pug
- var foo = [9, 5];

p.
  start #{foo.reduce(function (i, n) {
    return i + n;
  }, 7)} end
```

Disallowing this would be a breaking change as some users could legitimately think this was allowed.

This means (at least for the expression part), this could be kept as is or should be an opt-in.

**Comment by kylekatarnls** [comment]
With the version 1.8.0:

- Multi-line tag interpolations `#[\n]` will throw a dedicated exception.
- Multi-line expression interpolations `#{\n}` will throw a dedicated exception if `'multiline_interpolation'` option is set to `false`.
