### ISSUE TITLE
Variable is printing twice

### ISSUE THREAD

**Issue by trentwiles** [phug-php/phug#77]
Content is output twice with:
```pug
#{content}
```

From: https://stackoverflow.com/questions/64861822/phug-php-variable-is-printing-twice

**Comment by kylekatarnls** [comment]
What you see is `#{content}` which is a dynamic tag:

```pug
- content = 'div'
#{content} Foo
```

(same in Phug or Pug.js)

renders:
```
<div>Foo</div>
```

To insert a variable as raw html content, you simply need:
```pug
!=content
```

Or first a text node:
```pug
| !{content}
```

Note than you shouldn't use `htmlspecialchars` if you already escape in the template: `| #{content}` is escaped, `| !{content}` is displayed raw, `=content` is escaped, `!=content` is raw.

**Comment by trentwiles** [comment]
Thank you!
