### ISSUE TITLE
What documentation to use for pug-php?

### ISSUE THREAD

**Issue by mhf-ir** [phug-php/phug#8]
project https://github.com/pug-php/pug/ using nodejs engine i need to native php compiler without nodejs dependency.

**Comment by kylekatarnls** [comment]
The new documentation is not finished: https://phug.selfbuild.fr

This is open source, so you can help us to complete and translate: https://github.com/phug-php/website

Right now, the reliable documentation for pug-php is the [README](https://github.com/pug-php/pug/#pugphp) + https://pugjs.org/ specifications.

About nodejs, I think you're confused.

By default on version 3, https://github.com/pug-php/pug use the phug engine (it's full-PHP).

You can set `pugjs` option to `true` to use the nodejs engine instead, but it's not the default behavior.

**Comment by mhf-ir** [comment]
Than a lot add home page url in your user info https://github.com/phug-php. I think it's an experience for github users.

Using https://github.com/pug-php/pug `pug-js` install by default npm package that's so creepy for php project. i think it's must be an option not the default behavior.

**Comment by kylekatarnls** [comment]
When the doc will be completed, every GitHub projects URLs and READMEs will link to it.

Indeed, now with composer tools we could ask for the user to pre-install or not the `pugjs` package. It's a **pug-php** specific problem, so I will open an issue on it.

**Comment by kylekatarnls** [comment]
With pug-php 3.0.1, pug-cli will be asked to the user before install.
