### ISSUE TITLE
Breaking change 1.8 -> 1.9 of `a(href=$url)&attributes($attribs)`

### ISSUE THREAD

**Issue by rulatir** [phug-php/phug#88]
Hello,

I encountered a breaking change between 1.8 and 1.9:
```pug
a(href=$url)&attributes($attribs)
```
Assuming `$url === "foo"` and `$attribs['href'] === "bar"`, in 1.8 I got:

```html
<a href="foo"></a>
```

But in 1.9 I get:
```html
<a href="bar"></a>
```

Looks like in 1.8 explicitly specified attributes took precedence over the attributes bag, but in 1.9 it's just left-to-right, last one wins.

**Comment by kylekatarnls** [comment]
Hello,

This fix is related to #86 with the aim to align to pugjs and to support the automatically seeded `$attributes` array (coming from explicit attributes passed to the mixin call).

I think you could use:

```pug
mixin link()
  - unset($attribs['href'])
  a(href="#")&attributes($attribs)

link()(href="/")
```
This way you explicitly show that you ignore `href` from `$attribs` and you would get the desired output.

**Comment by rulatir** [comment]
This is nonetheless a breaking change. Is there a place I can monitor to know about breaking changes to this library in advance?

**Comment by rulatir** [comment]
Is there a solution that doesn't require fixing a hundred views in a thousand places, each requiring careful consideration and debugging? Is it possible to _write_ something that will do what `&attributes()` _used to_ do, and search/replace all occurrences of `&attributes()` with it?

**Comment by kylekatarnls** [comment]
Hello, in the next version (can be already tested requiring `composer require "phug/phug:dev-master as 1.12.0"`), the option `'attribute_precedence' => 'attribute',` can be used to give precedence to attributes over assignments, or `'attribute_precedence' => 'left',` to give priority to the most-left token.
